config/routes.rb
HasManyThrough::Application.routes.draw do
  resources :insurances

  resources :specialists

  resources :appointments

  resources :patients

end

app/models/specialist.rb
class Specialist < ActiveRecord::Base

  has_many :appointments

  has_many :patients, :through => :appointments

end

app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  # GET /specialists
  # GET /specialists.json
  def index
    @specialists = Specialist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specialists }
    end
  end

  # GET /specialists/1
  # GET /specialists/1.json
  def show
    @specialist = Specialist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @specialist }
    end
  end

  # GET /specialists/new
  # GET /specialists/new.json
  def new
    @specialist = Specialist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @specialist }
    end
  end

  # GET /specialists/1/edit
  def edit
    @specialist = Specialist.find(params[:id])
  end

  # POST /specialists
  # POST /specialists.json
  def create
    @specialist = Specialist.new(params[:specialist])

    respond_to do |format|
      if @specialist.save
        format.html { redirect_to @specialist, notice: 'Specialist was successfully created.' }
        format.json { render json: @specialist, status: :created, location: @specialist }
      else
        format.html { render action: "new" }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specialists/1
  # PUT /specialists/1.json
  def update
    @specialist = Specialist.find(params[:id])

    respond_to do |format|
      if @specialist.update_attributes(params[:specialist])
        format.html { redirect_to @specialist, notice: 'Specialist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialists/1
  # DELETE /specialists/1.json
  def destroy
    @specialist = Specialist.find(params[:id])
    @specialist.destroy

    respond_to do |format|
      format.html { redirect_to specialists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/views/specialists/_form.html.erb
<%= form_for(@specialist) do |f| %>
  <% if @specialist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@specialist.errors.count, "error") %> prohibited this specialist from being saved:</h2>

      <ul>
      <% @specialist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :specialty %><br />
    <%= f.text_field :specialty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specialists/edit.html.erb
<h1>Editing specialist</h1>

<%= render 'form' %>

<%= link_to 'Show', @specialist %> |
<%= link_to 'Back', specialists_path %>

app/views/specialists/index.html.erb
<h1>Listing specialists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Specialty</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specialists.each do |specialist| %>
  <tr>
    <td><%= specialist.name %></td>
    <td><%= specialist.specialty %></td>
    <td><%= link_to 'Show', specialist %></td>
    <td><%= link_to 'Edit', edit_specialist_path(specialist) %></td>
    <td><%= link_to 'Destroy', specialist, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Specialist', new_specialist_path %>

app/views/specialists/new.html.erb
<h1>New specialist</h1>

<%= render 'form' %>

<%= link_to 'Back', specialists_path %>

app/views/specialists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @specialist.name %>
</p>

<p>
  <b>Specialty:</b>
  <%= @specialist.specialty %>
</p>

<p>
  <strong>Pending Appointments</strong>
  <% @specialist.appointments.each do |app|%>
  <%= app.patient.name%>
  <%= app.appointment_date %>
  <%= (Date.today - app.appointment_date).to_int %>
      <%end%>
</p>

<%= link_to 'Edit', edit_specialist_path(@specialist) %> |
<%= link_to 'Back', specialists_path %>