config/routes.rb
HasManyThrough::Application.routes.draw do
  resources :insurances

  resources :specialists

  resources :appointments

  resources :patients

end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  has_many :patients
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  # GET /insurances
  # GET /insurances.json
  def index
    @insurances = Insurance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @insurances }
    end
  end

  # GET /insurances/1
  # GET /insurances/1.json
  def show
    @insurance = Insurance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @insurance }
    end
  end

  # GET /insurances/new
  # GET /insurances/new.json
  def new
    @insurance = Insurance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @insurance }
    end
  end

  # GET /insurances/1/edit
  def edit
    @insurance = Insurance.find(params[:id])
  end

  # POST /insurances
  # POST /insurances.json
  def create
    @insurance = Insurance.new(params[:insurance])

    respond_to do |format|
      if @insurance.save
        format.html { redirect_to @insurance, notice: 'Insurance was successfully created.' }
        format.json { render json: @insurance, status: :created, location: @insurance }
      else
        format.html { render action: "new" }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /insurances/1
  # PUT /insurances/1.json
  def update
    @insurance = Insurance.find(params[:id])

    respond_to do |format|
      if @insurance.update_attributes(params[:insurance])
        format.html { redirect_to @insurance, notice: 'Insurance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurances/1
  # DELETE /insurances/1.json
  def destroy
    @insurance = Insurance.find(params[:id])
    @insurance.destroy

    respond_to do |format|
      format.html { redirect_to insurances_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/views/insurances/_form.html.erb
<%= form_for(@insurance) do |f| %>
  <% if @insurance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insurance.errors.count, "error") %> prohibited this insurance from being saved:</h2>

      <ul>
      <% @insurance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insurances/edit.html.erb
<h1>Editing insurance</h1>

<%= render 'form' %>

<%= link_to 'Show', @insurance %> |
<%= link_to 'Back', insurances_path %>

app/views/insurances/index.html.erb
<h1>Listing insurances</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Street address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @insurances.each do |insurance| %>
  <tr>
    <td><%= insurance.name %></td>
    <td><%= insurance.street_address %></td>
    <td><%= link_to 'Show', insurance %></td>
    <td><%= link_to 'Edit', edit_insurance_path(insurance) %></td>
    <td><%= link_to 'Destroy', insurance, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Insurance', new_insurance_path %>

app/views/insurances/new.html.erb
<h1>New insurance</h1>

<%= render 'form' %>

<%= link_to 'Back', insurances_path %>

app/views/insurances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @insurance.name %>
</p>

<p>
  <b>Street address:</b>
  <%= @insurance.street_address %>
</p>


<%= link_to 'Edit', edit_insurance_path(@insurance) %> |
<%= link_to 'Back', insurances_path %>