config/routes.rb
HasManyThrough::Application.routes.draw do
  resources :insurances

  resources :specialists

  resources :appointments

  resources :patients

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :patient
  belongs_to :specilist

  def days_until_appointment
    (appointment_date - Date.today).to_int
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointments }
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/new
  # GET /appointments/new.json
  def new
    @appointment = Appointment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/1/edit
  def edit
    @appointment = Appointment.find(params[:id])
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(params[:appointment])

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render json: @appointment, status: :created, location: @appointment }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointments/1
  # PUT /appointments/1.json
  def update
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      if @appointment.update_attributes(params[:appointment])
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id %><br />
    <%= f.collection_select :patient_id, Patient.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :specialist_id %><br />
    <%= f.collection_select :specialist_id, Specialist.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :complaint %><br />
    <%= f.text_area :complaint %>
  </div>
  <div class="field">
    <%= f.label :appointment_date %><br />
    <%= f.date_select :appointment_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <tr>
    <th>Patient</th>
    <th>Specialist</th>
    <th>Complaint</th>
    <th>Appointment date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @appointments.each do |appointment| %>
  <tr>
    <td><%= appointment.patient.name %></td>
    <td><%= appointment.specialist.name %></td>
    <td><%= appointment.complaint %></td>
    <td><%= appointment.appointment_date %></td>
    <td><%= link_to 'Show', appointment %></td>
    <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
    <td><%= link_to 'Destroy', appointment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Patient:</b>
  <%= @appointment.patient.name %>
</p>

<p>
  <b>Specialist:</b>
  <%= @appointment.specialist.name %>
</p>

<p>
  <b>Complaint:</b>
  <%= @appointment.complaint %>
</p>

<p>
  <b>Appointment date:</b>
  <%= @appointment.appointment_date %>
</p>


<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>